// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  blogs: create.doc("blogs", {"design-foundations.mdx": () => import("../content/blogs/design-foundations.mdx?collection=blogs"), "fonts_broke_in_release.mdx": () => import("../content/blogs/fonts_broke_in_release.mdx?collection=blogs"), "homeScreen_widget.mdx": () => import("../content/blogs/homeScreen_widget.mdx?collection=blogs"), "how-to-publish-app-in-playstore.mdx": () => import("../content/blogs/how-to-publish-app-in-playstore.mdx?collection=blogs"), "how-to-run-flutter-apps-on-physicalDevice.mdx": () => import("../content/blogs/how-to-run-flutter-apps-on-physicalDevice.mdx?collection=blogs"), "how-to-set-app-icon-in-flutter.mdx": () => import("../content/blogs/how-to-set-app-icon-in-flutter.mdx?collection=blogs"), "how-to-use-custom-fonts-in-expo-with-nativewind.mdx": () => import("../content/blogs/how-to-use-custom-fonts-in-expo-with-nativewind.mdx?collection=blogs"), "how_to_use_animations_package.mdx": () => import("../content/blogs/how_to_use_animations_package.mdx?collection=blogs"), "how_to_use_hive.mdx": () => import("../content/blogs/how_to_use_hive.mdx?collection=blogs"), "programming-foundations.mdx": () => import("../content/blogs/programming-foundations.mdx?collection=blogs"), "react-native-errors.mdx": () => import("../content/blogs/react-native-errors.mdx?collection=blogs"), "rn-to-flutter.mdx": () => import("../content/blogs/rn-to-flutter.mdx?collection=blogs"), "what-is-bad-in-reactnative.mdx": () => import("../content/blogs/what-is-bad-in-reactnative.mdx?collection=blogs"), "work-with-Assests-in-flutter.mdx": () => import("../content/blogs/work-with-Assests-in-flutter.mdx?collection=blogs"), }),
  learn: create.doc("learn", {"index.mdx": () => import("../content/learn/index.mdx?collection=learn"), "dart-programming/1.intro.mdx": () => import("../content/learn/dart-programming/1.intro.mdx?collection=learn"), "dart-programming/2.variables_nullSafety.mdx": () => import("../content/learn/dart-programming/2.variables_nullSafety.mdx?collection=learn"), "dart-programming/3.controlFlow.mdx": () => import("../content/learn/dart-programming/3.controlFlow.mdx?collection=learn"), "dart-programming/4.operators.mdx": () => import("../content/learn/dart-programming/4.operators.mdx?collection=learn"), "dart-programming/5.functions.mdx": () => import("../content/learn/dart-programming/5.functions.mdx?collection=learn"), "dart-programming/6.list_and_maps.mdx": () => import("../content/learn/dart-programming/6.list_and_maps.mdx?collection=learn"), "dart-programming/7.classes_object_interface copy.mdx": () => import("../content/learn/dart-programming/7.classes_object_interface copy.mdx?collection=learn"), "dart-programming/8.enums.mdx": () => import("../content/learn/dart-programming/8.enums.mdx?collection=learn"), "dart-programming/9.mixins.mdx": () => import("../content/learn/dart-programming/9.mixins.mdx?collection=learn"), "flutter-development/1.basics.mdx": () => import("../content/learn/flutter-development/1.basics.mdx?collection=learn"), "flutter-development/2.working_with_images_in_flutter.mdx": () => import("../content/learn/flutter-development/2.working_with_images_in_flutter.mdx?collection=learn"), }),
};
export default browserCollections;