import type { Metadata } from "next";
import {
  BBH_Sans_Bogle,
  Geist,
  Geist_Mono,
  Inter,
  Poppins,
  Source_Serif_4,
} from "next/font/google";
import "./globals.css";
import { RootProvider } from "fumadocs-ui/provider/next";
import MainFooter from "@/components/footer";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Source_Serif_4({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const sourceSerif = Source_Serif_4({
  variable: "--font-source-serif",
  // subsets: ["latin", "latin-ext", "greek"],
});

const bbh = BBH_Sans_Bogle({
  variable: "--font-bbh",
  weight: "400",
});

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "AppykitUI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={` ${bbh.variable} 
    ${poppins.variable} font-poppins`}
    >
      {/* ${geistSans.variable} ${geistMono.variable} */}
      <body
        className={` 
            antialiased flex flex-col min-h-screen`}
      >
        <RootProvider>{children}</RootProvider>
        <MainFooter />
      </body>
    </html>
  );
}
